input:
  file:
    paths: ["./input.json"]
    codec: all-bytes

output: 
  cypher:
    Database: "neo4j" 
    Uri: "bolt://localhost:7687"
    NoAuth: true

### Auth Schemes 

# NoAuth 
# BasicAuth
# KerberosAuth
# BearerAuth 
# CustomAuth 

